#!/bin/bash
set -e

# Author: Pedro Freire www.pedrofreire.com
# License: MIT


# User-defined script configuration
# NOTE: If ~/dev-env.sh exists, its values override what's defined here
# ===========================================================================

# In these host directories, AI agents run with no restrictions
PROJECT_WHITELIST=(
	"$HOME/Documents/Software"
)

LOCALHOST_DNS_ALIAS=host.container.internal
LOCALHOST_IP_ALIAS=203.0.113.113
# https://github.com/apple/container/blob/main/docs/host-integration.md#access-a-host-service-from-a-container
# https://github.com/apple/container/blob/main/docs/command-reference.md#container-system-dns-create

VM_USER=user
VM_HOST=vm.local
VM_PORTS=(
	22    # SSH / SFTP
	80    # HTTP
	443   # HTTPS
)


# Override local configuration with ~/dev-env.sh
# ===========================================================================

if [[ -f "$HOME/dev-env.sh" ]]
then
	. "$HOME/dev-env.sh"

	((${#DEV_ENV_PROJECTS[@]}))  &&  PROJECT_WHITELIST=("${DEV_ENV_PROJECTS[@]}")

	LOCALHOST_DNS_ALIAS="${DEV_ENV_LOCALHOST_DNS_ALIAS:-$LOCALHOST_DNS_ALIAS}"
	LOCALHOST_IP_ALIAS="${DEV_ENV_LOCALHOST_IP_ALIAS:-$LOCALHOST_IP_ALIAS}"

	VM_USER="${DEV_ENV_VM_USER:-$VM_USER}"
	VM_HOST="${DEV_ENV_VM_HOST:-$VM_HOST}"
	((${#DEV_ENV_VM_PORTS[@]}))  &&  VM_PORTS=("${DEV_ENV_VM_PORTS[@]}")
fi


# Constants
# ===========================================================================

SSH_SOCKET="/tmp/agent-start-vm-tunnel.$UID.sock"
DNS_ALIAS_LIST="/tmp/agent-start-dns-alias.$UID.txt"


# Parse the command-line arguments
# ===========================================================================

is_single_project=true
has_ssh_access=false
has_vm_access=false
has_host_localhost_access=false

while [[ $# -gt 0 ]]
do
	case ".$1" in
		".claude"|".claude-code")
			agent_container=agent-claude
			agent_env=(                      \
				--env DISABLE_UPDATES=1      \
				--env DISABLE_AUTOUPDATER=1  \
				--env ANTHROPIC_API_KEY      \
			)
			agent_env_unsafe=()
			agent_exec=claude
			agent_args=()
			agent_args_unsafe=(                      \
				--permission-mode bypassPermissions  \
				--dangerously-skip-permissions       \
			)
			;;
		".codex"|".chatgpt")
			agent_container=agent-codex
			agent_env=()
			agent_env_unsafe=()
			agent_exec=codex
			agent_args=()
			agent_args_unsafe=(                             \
				--config check_for_update_on_startup=false  \
				--sandbox danger-full-access                \
				--dangerously-bypass-approvals-and-sandbox  \
			)
			;;
		".antigravity")
			agent_container=agent-antigravity
			agent_env=(--env AGY_CLI_DISABLE_AUTO_UPDATE=true)
			agent_env_unsafe=()
			agent_exec=agy
			agent_args=()
			agent_args_unsafe=(--dangerously-skip-permissions)
			;;
		".gemini")
			agent_container=agent-gemini
			agent_env=()
			agent_env_unsafe=()
			agent_exec=gemini
			agent_args=()
			agent_args_unsafe=(--yolo)
			;;
		".vibe"|".mistral"|".mistral-vibe")
			agent_container=agent-vibe
			agent_env=(                                \
				--env VIBE_ENABLE_AUTO_UPDATE=false    \
				--env VIBE_ENABLE_UPDATE_CHECKS=false  \
				--env MISTRAL_API_KEY                  \
			)
			agent_env_unsafe=()
			agent_exec=vibe
			agent_args=()
			agent_args_unsafe=(--yolo)
			;;
		".opencode"|".open-code"|".oc")
			agent_container=agent-opencode
			agent_env=(--env OPENCODE_DISABLE_AUTOUPDATE=true)
			agent_env_unsafe=(--env OPENCODE_PERMISSION='{"*":"allow"}')
			agent_exec=opencode
			agent_args=()
			agent_args_unsafe=(--auto)
			;;
		".-h"|".--help")
			script_name="$(basename "$0")"
			if [ "$script_name" = "agent-start" ]
			then
				usage_agent=" <agent>"
			else
				usage_agent=""
			fi
			echo
			echo "Usage:"
			echo "    $script_name$usage_agent [<options>, ...] [-|-- [<agent-option>, ...]]"
			echo
			echo "Agents:"
			echo "  claude"
			echo "  codex"
			echo "  antigravity, agy"
			echo "  gemini"
			echo "  vibe"
			echo "  opencode"
			echo
			echo "Options:"
			echo "  -a,  --all          Map all project dirs (\$PROJECT_WHITELIST) to allow the agent to work across"
			echo "                      projects."
			echo "  -s,  --sh           Run the container shell, not the agent itself."
			echo "       --ssh          Map ~/.ssh/* files to allow the agent to access to servers/Virtual Machines."
			echo "  -l,  --local        Create a container DNS '$LOCALHOST_DNS_ALIAS' that maps to the host's localhost,"
			echo "                      via $LOCALHOST_IP_ALIAS. Required to access Ollama, LM Studio, MTPLX models,"
			echo "                      VMs, or other services running on the host. This DNS entry is persistent across"
			echo "                      all future invocations of agents, until a reboot. Environment vars"
			echo "                      LOCALHOST_DNS_ALIAS and LOCALHOST_IP_ALIAS are passed to the agent for reuse."
			echo "                      This is incompatible with iCloud Private Relay."
			echo "  -l-, --local-del    Delete DNS entry created by -l, --local, and exit."
			echo "       --vm           Setup SSH tunnels to allow the agent to access a host VM ('$VM_USER@$VM_HOST')"
			echo "                      using Shared Network. Not required for Bridged Network."
			echo "                      This SSH tunnel is persistent across all future invocations of agents, until"
			echo "                      the VM shuts down. Implies --local."
			echo "                      This is incompatible with services running in the host in the same ports"
			echo "                      (${VM_PORTS[*]})."
			echo "       --vm-del       Close the SSH tunnel created by --vm, and exit. Does not do a --local-del."
			echo "  -c,  --connect      Combined --ssh, --local and --vm."
			echo
			echo "All -l, --local, --vm also create DNS aliases inside the container, that match host /etc/hosts DNS"
			echo "aliases pointing to 127.0.0.1 or the VM's '$VM_HOST' IP. All DNS aliases inside the container will"
			echo "point to $LOCALHOST_IP_ALIAS. This ensures they match functionality on the host and container."
			echo
			echo "Pass options to the agent:"
			echo "  -  <agent-options>  Pass options along with the default options determined by this script."
			echo "  -- <agent-options>  Pass ONLY the options specified."
			echo
			exit 0
			;;
		".-a"|".--all")
			is_single_project=false
			;;
		".-s"|".--sh")
			agent_exec=bash
			agent_args=()
			agent_args_unsafe=()
			;;
		".--ssh")
			has_ssh_access=true
			;;
		".-l"|".--local")
			has_host_localhost_access=true
			;;
		".-l-"|".--local-del")
			echo "Deleting DNS record '$LOCALHOST_DNS_ALIAS' (requires sudo)"
			sudo container system dns delete "$LOCALHOST_DNS_ALIAS"
			echo
			echo "Restarting container system"
			container system stop
			container system start
			exit 0
			;;
		".--vm")
			has_vm_access=true
			has_host_localhost_access=true
			;;
		".--vm-"|".--vm-del"|".--vm-close")
			# This is failing (2026-08), likely due to bugs:
			# https://github.com/apple/container/issues/817
			# https://github.com/apple/container/issues/1794
			#
			#echo "Deleting DNS aliases to localhost/VM (requires sudo)"
			if [ -f "$DNS_ALIAS_LIST" ]
			then
			#	while read -r name; do
			#		sudo container system dns delete $name  ||  true
			#	done < "$DNS_ALIAS_LIST"
				rm "$DNS_ALIAS_LIST"
			fi
			#echo
			echo "Testing for existing tunnel to VM '$VM_HOST' (requires sudo)"
			if sudo ssh -S "$SSH_SOCKET" -O check "${VM_USER}@${VM_HOST}" 2>/dev/null
			then
				echo
				echo "Closing tunnel to VM '$VM_HOST' (requires sudo)"
				sudo ssh -S "$SSH_SOCKET" -O exit "${VM_USER}@${VM_HOST}"
			fi
			if [ -f "$SSH_SOCKET" ]
			then
				rm "$SSH_SOCKET"
			fi
			exit 0
			;;
		".-c"|".--connect"|".--combined")
			has_ssh_access=true
			has_vm_access=true
			has_host_localhost_access=true
			;;
		".-")
			shift
			break
			;;
		".--")
			shift
			agent_args=()
			agent_args_unsafe=()
			break
			;;
		*)
			echo "Missing or unknown AI agent ('$1') as argument."
			exit 1
			;;
	esac
	shift
done


# Determine current woking directory (WORKSPACE)
# ===========================================================================

WORKSPACE="$(pwd)"

if [ "$WORKSPACE" == "$HOME" ] || [ "$WORKSPACE" == "$HOME/Documents" ]
then
	echo
	echo "You're running me from ~ or ~/Documents."
	echo "All of your documents will be shared with the agent."
	echo "Proceed? [N]"
	read -r confirm
	if [ "$confirm" != "Y" ]  &&  [ "$confirm" != "y" ]
	then
		exit 1
	fi
fi


# Check if WORKSPACE is one of the white-listed directories for unsafe agents
# ===========================================================================

is_whitelisted=false
for whitelist_dir in "${PROJECT_WHITELIST[@]}"
do
	if [[ "$WORKSPACE" == "$whitelist_dir" || "$WORKSPACE" == "$whitelist_dir/"* ]]
	then
		is_whitelisted=true
		agent_env+=("${agent_env_unsafe[@]}")
		agent_args+=("${agent_args_unsafe[@]}")
		break
	fi
done


# Start Apple Container system
# ===========================================================================

if ! container system status &>/dev/null
then
	container system start
fi


# Define the data mount volumes and working dir for the AI agent
# ===========================================================================

CONTAINER_WORKSPACE="/home/agent${WORKSPACE#"$HOME"}"

if ! $is_whitelisted
then

	volumes=(--volume "$WORKSPACE:/home/agent/workspace")
	workdir=/home/agent/workspace

elif $is_single_project
then

	volumes=(--volume "$WORKSPACE:$CONTAINER_WORKSPACE")
	workdir="$CONTAINER_WORKSPACE"

else  # ! $is_single_project

	# With all projects mounted, use a similar directory structure,
	# so that these cross-references work:
	#	~/Documents/...
	#	../../another_project/...

	volumes=()
	for whitelist_dir in "${PROJECT_WHITELIST[@]}"
	do
		container_dir="/home/agent${whitelist_dir#"$HOME"}"
		volumes+=(--volume "$whitelist_dir:$container_dir")
	done
	workdir="$CONTAINER_WORKSPACE"

fi


# Start the AI agent's local (VM) domains
# ===========================================================================
if $has_vm_access
then
	# This is failing (2026-08), likely due to bugs:
	# https://github.com/apple/container/issues/817
	# https://github.com/apple/container/issues/1794
	#
	#echo "Creating DNS aliases to localhost/VM (requires sudo)"
	#if [ -f "$DNS_ALIAS_LIST" ]
	#then
	#	echo "Aliases already created"
	#else
	#	VM_IP=$(awk "\$2 == \"$VM_HOST\" {print \$1}" /etc/hosts)
	#	awk "{ sub(/#.*/, \"\"); if (\$1 == \"127.0.0.1\" || \$1 == \"$VM_IP\") for (i=2;i<=NF;i++) print \$i }" /etc/hosts \
	#		| grep -vE '^(localhost|localhost\.localdomain|broadcasthost)$' > "$DNS_ALIAS_LIST"
	#	while read -r name; do
	#		sudo container system dns create $name --localhost $LOCALHOST_IP_ALIAS
	#	done < "$DNS_ALIAS_LIST"
	#fi
	#echo
	echo "Testing for existing tunnel to VM '$VM_HOST' (requires sudo)"
	if ! sudo ssh -S "$SSH_SOCKET" -O check "${VM_USER}@${VM_HOST}" 2>/dev/null
	then
		port_links=()
		for port in "${VM_PORTS[@]}"
		do
			port_links+=(-L 127.0.0.1:"${port}":127.0.0.1:"${port}")
		done
		echo
		echo "Establishing tunnel to VM '$VM_HOST' (requires sudo)"
		sudo ssh -f -N                    \
			-o ControlMaster=yes          \
			-o ControlPath="$SSH_SOCKET"  \
			-o ControlPersist=yes         \
			-o ExitOnForwardFailure=yes   \
			-o ServerAliveInterval=30     \
			-o ServerAliveCountMax=3      \
			"${port_links[@]}"            \
			"${VM_USER}@${VM_HOST}"
	fi
fi


# Start the DNS records for accessing the host's localhost inside the container
# ===========================================================================
if $has_host_localhost_access
then
	echo "Recreating DNS record '$LOCALHOST_DNS_ALIAS' (requires sudo)"
	sudo container system dns delete "$LOCALHOST_DNS_ALIAS"  >/dev/null 2>&1  ||  true
	sudo container system dns create "$LOCALHOST_DNS_ALIAS" --localhost "$LOCALHOST_IP_ALIAS"
fi


# Prepare the hosts alias file to be sent to the container
# ===========================================================================
if $has_vm_access || $has_host_localhost_access
then
	if [ ! -f "$DNS_ALIAS_LIST" ]
	then
		VM_IP=$(awk "\$2 == \"$VM_HOST\" {print \$1}" /etc/hosts)
		awk "{ sub(/#.*/, \"\"); if (\$1 == \"127.0.0.1\" || \$1 == \"$VM_IP\") for (i=2;i<=NF;i++) print \$i }" /etc/hosts \
			| grep -vE '^(localhost|localhost\.localdomain|broadcasthost)$' > "$DNS_ALIAS_LIST"
	fi
fi
if [ -f "$DNS_ALIAS_LIST" ]
then
	volumes+=(--volume "$DNS_ALIAS_LIST:/etc/host-aliases.txt")
fi


# Start the AI agent's container
# ===========================================================================

case $agent_container in

	"agent-claude")
		if $has_ssh_access
		then
			volumes+=(
				--volume "$HOME/.ssh/ssh-agent-claude.pem:/home/agent/.ssh/ssh-agent-claude.pem:ro"
				--volume "$HOME/.ssh/ssh-agent-claude.pem.pub:/home/agent/.ssh/ssh-agent-claude.pem.pub:ro"
				--volume "$HOME/.ssh/config-agent-claude:/home/agent/.ssh/config:ro"
				--volume "$HOME/.ssh/known_hosts_agents:/home/agent/.ssh/known_hosts:ro"
				)
		fi
		exec container run -it --rm                           \
			--cpus 2 --memory 4G                              \
			--progress none                                   \
			"${volumes[@]}"                                   \
			--volume "$HOME/Documents/Corebase/Software/Workspaces/Containers/Claude/!claude:/home/agent/.claude"  \
			--volume "$HOME/Documents/Corebase/Software/Workspaces/Containers/Claude/!claude.json:/home/agent/.claude.json"  \
			--volume "$HOME/Documents/Corebase/Software/Workspaces/Containers/Claude/!config:/home/agent/.config"  \
			--workdir "$workdir"                              \
			--env LOCALHOST_DNS_ALIAS="$LOCALHOST_DNS_ALIAS"  \
			--env LOCALHOST_IP_ALIAS="$LOCALHOST_IP_ALIAS"    \
			--env COLORTERM                                   \
			--env TERM                                        \
			"${agent_env[@]}"                                 \
			"$agent_container" "$agent_exec" "$@" "${agent_args[@]}"
		;;

	"agent-codex")
		if $has_ssh_access
		then
			volumes+=(
				--volume "$HOME/.ssh/ssh-agent-codex.pem:/home/agent/.ssh/ssh-agent-codex.pem:ro"
				--volume "$HOME/.ssh/ssh-agent-codex.pem.pub:/home/agent/.ssh/ssh-agent-codex.pem.pub:ro"
				--volume "$HOME/.ssh/config-agent-codex:/home/agent/.ssh/config:ro"
				--volume "$HOME/.ssh/known_hosts_agents:/home/agent/.ssh/known_hosts:ro"
				)
		fi
		exec container run -it --rm                           \
			--cpus 2 --memory 4G                              \
			--progress none                                   \
			"${volumes[@]}"                                   \
			--volume "$HOME/Documents/Corebase/Software/Workspaces/Containers/Codex/!codex:/home/agent/.codex"  \
			--workdir "$workdir"                              \
			--env LOCALHOST_DNS_ALIAS="$LOCALHOST_DNS_ALIAS"  \
			--env LOCALHOST_IP_ALIAS="$LOCALHOST_IP_ALIAS"    \
			--env COLORTERM                                   \
			--env TERM                                        \
			"${agent_env[@]}"                                 \
			"$agent_container" "$agent_exec" "$@" "${agent_args[@]}"
		;;

	"agent-antigravity")
		if $has_ssh_access
		then
			volumes+=(
				--volume "$HOME/.ssh/ssh-agent-gemini.pem:/home/agent/.ssh/ssh-agent-gemini.pem:ro"
				--volume "$HOME/.ssh/ssh-agent-gemini.pem.pub:/home/agent/.ssh/ssh-agent-gemini.pem.pub:ro"
				--volume "$HOME/.ssh/config-agent-gemini:/home/agent/.ssh/config:ro"
				--volume "$HOME/.ssh/known_hosts_agents:/home/agent/.ssh/known_hosts:ro"
				)
		fi
		exec container run -it --rm                           \
			--cpus 2 --memory 4G                              \
			--progress none                                   \
			"${volumes[@]}"                                   \
			--volume "$HOME/Documents/Corebase/Software/Workspaces/Containers/Antigravity/!gemini:/home/agent/.gemini"  \
			--workdir "$workdir"                              \
			--env LOCALHOST_DNS_ALIAS="$LOCALHOST_DNS_ALIAS"  \
			--env LOCALHOST_IP_ALIAS="$LOCALHOST_IP_ALIAS"    \
			--env COLORTERM                                   \
			--env TERM                                        \
			"${agent_env[@]}"                                 \
			"$agent_container" "$agent_exec" "$@" "${agent_args[@]}"
		;;

	"agent-gemini")
		if $has_ssh_access
		then
			volumes+=(
				--volume "$HOME/.ssh/ssh-agent-gemini.pem:/home/agent/.ssh/ssh-agent-gemini.pem:ro"
				--volume "$HOME/.ssh/ssh-agent-gemini.pem.pub:/home/agent/.ssh/ssh-agent-gemini.pem.pub:ro"
				--volume "$HOME/.ssh/config-agent-gemini:/home/agent/.ssh/config:ro"
				--volume "$HOME/.ssh/known_hosts_agents:/home/agent/.ssh/known_hosts:ro"
				)
		fi
		exec container run -it --rm                           \
			--cpus 2 --memory 4G                              \
			--progress none                                   \
			"${volumes[@]}"                                   \
			--volume "$HOME/Documents/Corebase/Software/Workspaces/Containers/Gemini/!gemini:/home/agent/.gemini"  \
			--workdir "$workdir"                              \
			--env LOCALHOST_DNS_ALIAS="$LOCALHOST_DNS_ALIAS"  \
			--env LOCALHOST_IP_ALIAS="$LOCALHOST_IP_ALIAS"    \
			--env COLORTERM                                   \
			--env TERM                                        \
			"${agent_env[@]}"                                 \
			"$agent_container" "$agent_exec" "$@" "${agent_args[@]}"
		;;

	"agent-vibe")
		if $has_ssh_access
		then
			volumes+=(
				--volume "$HOME/.ssh/ssh-agent-vibe.pem:/home/agent/.ssh/ssh-agent-vibe.pem:ro"
				--volume "$HOME/.ssh/ssh-agent-vibe.pem.pub:/home/agent/.ssh/ssh-agent-vibe.pem.pub:ro"
				--volume "$HOME/.ssh/config-agent-vibe:/home/agent/.ssh/config:ro"
				--volume "$HOME/.ssh/known_hosts_agents:/home/agent/.ssh/known_hosts:ro"
				)
		fi
		exec container run -it --rm                           \
			--cpus 2 --memory 4G                              \
			--progress none                                   \
			"${volumes[@]}"                                   \
			--volume "$HOME/Documents/Corebase/Software/Workspaces/Containers/Vibe/!vibe:/home/agent/.vibe"  \
			--workdir "$workdir"                              \
			--env LOCALHOST_DNS_ALIAS="$LOCALHOST_DNS_ALIAS"  \
			--env LOCALHOST_IP_ALIAS="$LOCALHOST_IP_ALIAS"    \
			--env COLORTERM                                   \
			--env TERM                                        \
			"${agent_env[@]}"                                 \
			"$agent_container" "$agent_exec" "$@" "${agent_args[@]}"
		;;

	"agent-opencode")
		if $has_ssh_access
		then
			volumes+=(
				--volume "$HOME/.ssh/ssh-agent-opencode.pem:/home/agent/.ssh/ssh-agent-opencode.pem:ro"
				--volume "$HOME/.ssh/ssh-agent-opencode.pem.pub:/home/agent/.ssh/ssh-agent-opencode.pem.pub:ro"
				--volume "$HOME/.ssh/config-agent-opencode:/home/agent/.ssh/config:ro"
				--volume "$HOME/.ssh/known_hosts_agents:/home/agent/.ssh/known_hosts:ro"
				)
		fi
		exec container run -it --rm                           \
			--cpus 2 --memory 4G                              \
			--progress none                                   \
			"${volumes[@]}"                                   \
			--volume "$HOME/Documents/Corebase/Software/Workspaces/Containers/OpenCode/!config:/home/agent/.config"  \
			--volume "$HOME/Documents/Corebase/Software/Workspaces/Containers/OpenCode/!local:/home/agent/.local"  \
			--workdir "$workdir"                              \
			--env LOCALHOST_DNS_ALIAS="$LOCALHOST_DNS_ALIAS"  \
			--env LOCALHOST_IP_ALIAS="$LOCALHOST_IP_ALIAS"    \
			--env COLORTERM                                   \
			--env TERM                                        \
			"${agent_env[@]}"                                 \
			"$agent_container" "$agent_exec" "$@" "${agent_args[@]}"
		;;

	*)
		echo "Unimplemented AI agent '$agent_container'."
		exit 1
		;;
esac


# exec container run -it --rm \
#	--cpus 2 --memory 4G \
#	--publish 127.0.0.1:1234:1234    \
#	--volume "$WORKSPACE:/workspace" \
#	--mount "type=bind,source=$HOME/Downloads,target=/home/agent/Downloads,readonly" \
#	--user agent
